# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.

name: bad-quote
on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  detector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check quotes
        run: .github/scripts/check-quotes.pl SUMMARY.md

