# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.

name: pdf
on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install prereqs
        run: |
          sudo apt-get update
          sudo apt-get install pandoc texlive-latex-base texlive-latex-recommended

      - name: build pdf
        run: make pdf
